version: "3.9"

services:
  flask_app:
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      FLASK_APP: sample_app
    volumes:
      - ./app/sample_app:/usr/src/app/sample_app
      - socket:/tmp
    depends_on:
      mysql:
        condition: service_healthy
  web:
    image: nginx:stable
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - socket:/tmp

  mysql:
    image: mysql
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/migrations:/docker-entrypoint-initdb.d
    environment:
      # replace here
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sample-db
      TZ: Asia/Tokyo
    cap_add:
      - SYS_NICE
    healthcheck:
      test: mysqladmin ping
      interval: 3s
      timeout: 3s
      retries: 10
      start_period: 1s

volumes:
  db_data:
  socket:
